### ISSUE TITLE
Checklist(7/6)

### ISSUE THREAD

**Issue by hskang9** [DeLeague/Detway#1]
# Frontend
- Sections
     - Versus 
        - [] Countdown
        - [] Competitor profile
        
     - Status
        - Line Chart
            - [] Total number of players
            - [] Total number of tokens staked
        - Pie Chart
            - [] Staked on Each team
     -  What is DLG?
            - [] Explanation for DLG
     -  Join Game
            - [] Token to stake
            - [] Stake button
            - [] Notification for transaction
